Web/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path, include, re_path


# handler404 = 'home.views.custom_404'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('accademics/', include('accademics.urls')),
    path('accreditation/', include('accreditation.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('hour/', include('hour.urls')),
    path('member/', include('member.urls')),
    path('price/', include('price.urls')),
    path('publication/', include('publication.urls')),
    path('register/', include('register.urls')),
    path('tesmonie/', include('testimonie.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^staticfiles/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]


about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name='index'),
]

accademics/urls.py
from django.urls import path

from . import views

app_name = 'accademics'
urlpatterns = [
    path('', views.index, name='index'),
]

accreditation/urls.py
from django.urls import path
from . import views

app_name = 'accreditation'
urlpatterns = [
    path('', views.index, name='index')
]

address/urls.py
from django.urls import path

from . import views

app_name = 'address'
urlpatterns = [
    path('', views.index, name='index'),
]

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact_us'
urlpatterns = [
    path('', views.ContactView.as_view(), name='index')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index')
]

hour/urls.py
from django.urls import path

from . import views

app_name = 'hour'
urlpatterns = [
    path('', views.index, name='index'),
]

member/urls.py
from django.urls import path

from . import views

app_name = 'member'
urlpatterns = [
    path('', views.index, name='index'),
]

new/urls.py
from . import views
from django.urls import path

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
]

price/urls.py
from django.urls import path

from . import views

app_name = 'price'
urlpatterns = [
    path('', views.index, name='index'),
]

publication/urls.py
from publication import views
from django.urls import path

app_name = 'publication'
urlpatterns = [
    path('', views.index, name='index'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.index, name='index')
]

testimonie/urls.py
from django.urls import path

from . import views

app_name = 'testimonie'
urlpatterns = [
    path('', views.index, name='index'),
]

blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from publication import models as pub_mod

from Web.utils import ImageModel, BaseModel

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(BaseModel, ImageModel):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(pub_mod.Author, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        db_table = "blog"
        verbose_name_plural = "Les Blogs"
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class Slogan(BaseModel, ImageModel):
    title = models.CharField(max_length=200, unique=True)
    note = models.CharField(max_length=200, null=True)
    description = models.TextField()

    class Meta:
        db_table = "slogan"
        verbose_name_plural = "Les Slogans"

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render
from . import models


# Create your views here.
def index(request):
    aboutes = models.Info.objects.all()
    context = {
        'current_page': request.path,
        'aboutes': aboutes
    }
    return render(request, 'about/index.html', context)

blog/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from .models import Post, Slogan


def index(request):
    queryset = Post.objects.filter(status=1).order_by('-created_at')
    slogan = Slogan.objects.all().first()
    context = {
        'current_page': request.path,
        'queryset': queryset,
        'slogan': slogan
    }
    return render(request, 'blog/index.html', context)

home/views.py
from django.shortcuts import render
from django.views import View
from django.core.exceptions import ObjectDoesNotExist
from accreditation import models as mdl
from . import models


# Create your views here.
class HomeView(View):
    def get(self, request):
        try:
            movies = models.PresentationVideo.objects.latest('created_at')
        except ObjectDoesNotExist:
            movies = None
        activities = models.Activity.objects.all()
        pictures = models.PresentationImage.objects.all()
        try:
            page_gardes = models.PageGarde.objects.latest('created_at')
        except ObjectDoesNotExist:
            page_gardes =  None
        try:
            memberships = models.Membership.objects.latest('created_at')
        except ObjectDoesNotExist:
            memberships = None

        lists = mdl.List.objects.all()
        context = {
            'current_page': request.path,
            'movies': movies,
            'pictures': pictures,
            'page_gardes': page_gardes,
            'activities': activities,
            'memberships': memberships,
            'lists': lists
        }
        return render(request, 'home/index.html', context)

hour/views.py
from django.shortcuts import render
from .models import Hour


# Create your views here.
def base_context(request):
    hours = Hour.get_current_hours()
    hour_lists = Hour.objects.all()

    context = {
        'hours_now': hours,
        'hour_lists': hour_lists
    }
    return context


def index(request):
    current_hours = Hour.get_current_hours()
    hours = Hour.objects.all()

    context = {
        'current_page': request.path,
        'current_hours': current_hours,
        'hours': hours
    }

    return render(request, 'hour/index.html', context)

new/views.py
from django.shortcuts import render
from .models import Post


# Create your views here.
def index(request):
    news = Post.objects.filter(status=1).order_by('-created_on')
    context = {
        'news': news
    }
    return render(request, 'news/index.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | American High School
    </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{% static 'assets/img/icon/icon.ico' %}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Quicksand:wght@600;700&display=swap" rel="stylesheet" />

    <!-- Font Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'assets/lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    {% block style %}{% endblock %}
</head>
<body>

    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    {% include 'layouts/partials/_topbar.html' %}
    {% include 'layouts/partials/_navbar.html' %}

    <main class="main-content">
        {% block content %}{% endblock %}
    </main>

    {% include 'layouts/partials/_footer.html' %}

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="{% static 'assets/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'assets/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'assets/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% block script %}{% endblock %}
</body>
</html>

templates/layouts/partials/_footer.html
<!-- Footer Start -->
<footer
   class="container-fluid footer bg-dark text-light footer mt-5 m-lg-auto wow fadeIn"
   data-wow-delay="0.1s"
   >
   <div class="container py-5">
      <div class="row g-5">
         <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4"></h5>
            <div class="mb-2">
               {% for address in addresses_ahsm %}
               <i class="fa fa-map-marker-alt me-3"></i>
               {{ address.lot }} {{ address.street }} {{ address.city }}
               {% endfor %}
            </div>
            {% for info in contacts_helps %}
            <div class="mb-2">
               <i class="fa fa-phone-alt me-3"></i>
               {{ info.number }}
            </div>
            {% endfor %}
            <div class="mb-2">
               <i class="fa fa-envelope me-3"></i>
                info@itti-americanhighschoolmada.com
{#               {{ info.email|truncatechars:25 }}#}
            </div>
            <div class="d-flex pt-2">
               {% if socials %}
               {% for social in socials %}
               <a class="btn btn-outline-light btn-social" href="{{ social.url }}"
                  ><i class="{{ social.social_type }}"></i
                  ></a>
               {% endfor %}
               {% endif %}
            </div>
         </div>
         <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4">Quick Links</h5>
            <a class="btn btn-link" href="{% url 'about:index' %}">About Us</a>
            <a class="btn btn-link" href="{% url 'contact_us:index' %}">Contact Us</a>
            <a class="btn btn-link" href="{% url 'member:index' %}">Membership</a>
            <a class="btn btn-link" href="#">Terms & Condition</a>
            <a class="btn btn-link" href="#">Support</a>
         </div>
         <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4">Popular Links</h5>
            <a class="btn btn-link" href="{% url 'about:index' %}">About Us</a>
            <a class="btn btn-link" href="{% url 'contact_us:index' %}">Contact Us</a>
            <a class="btn btn-link" href="{% url 'accademics:index' %}">Accademics</a>
            <a class="btn btn-link" href="#">Terms & Condition</a>
            <a class="btn btn-link" href="#">Support</a>
         </div>
         <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4">Newsletter</h5>
            <div class="mb-2">Si vous voulez être informer des nouveautés sur AHS.</div>
            <div class="position-relative mx-auto" style="max-width: 400px">
               <input
                  class="form-control border-0 w-100 py-3 ps-4 pe-5"
                  type="text"
                  placeholder="Your email"
                  />
               <button
                  type="button"
                  class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2"
                  >
               SignUp
               </button>
            </div>
         </div>
      </div>
   </div>
   <div class="container">
      <div class="copyright">
         <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
               &copy; <a class="border-bottom" href="{% url 'about:index' %}">AHS</a>, All
               Right Reserved.
            </div>
            <div class="col-md-6 text-center text-md-end">
               Designed By
               <a class="border-bottom" href="#"
                  >TSIDIANY Raharison Muriel</a
                  >
               <br />Distributed By:
               <a href="#" target="_blank">ITDevSuccess</a>
            </div>
         </div>
      </div>
   </div>
</footer>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
   ><i class="bi bi-arrow-up"></i
   ></a>

templates/layouts/partials/_navbar.html
{% load static %}
<!-- Navbar Start -->
<nav
  class="navbar navbar-expand-lg bg-white navbar-light sticky-top py-lg-0 px-4 px-lg-5 wow fadeIn"
  data-wow-delay="0.1s"
>
  <a href="#" class="navbar-brand p-0">
    <img class="img-fluid me-5" src="{% static 'assets/img/icon/logo.jpeg' %}" alt="Icon" />
{#    <h1 class="m-0 text-primary">ITTI</h1>#}
  </a>
  <button
    type="button"
    class="navbar-toggler"
    data-bs-toggle="collapse"
    data-bs-target="#navbarCollapse"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse py-4 py-lg-0" id="navbarCollapse">
    <div class="navbar-nav ms-auto">
      <a href="{% url 'home:index' %}" class="nav-item nav-link {% if current_page == '/' %}active{% endif %}" >Home</a>
      <a href="{% url 'about:index' %}" class="nav-item nav-link {% if current_page == '/about/' %}active{% endif %}">About Us</a>
      <a href="{% url 'accademics:index' %}" class="nav-item nav-link {% if current_page == '/accademics/' %}active{% endif %}">Accademics</a>
{#      <a href="{% url 'publication:index' %}" class="nav-item nav-link position-relative {% if current_page == '/publication/' %}active{% endif %} ">#}
{#          News#}
{#          <span#}
{#              class="position-absolute top-15 start-100 translate-middle#}
{#               badge border border-light rounded-circle bg-danger p-1">#}
{#              <span class="visually-hidden">unread messages</span>#}
{#          </span>#}
{#      </a>#}
      <a href="{% url 'blog:index' %}" class="nav-item nav-link {% if current_page == '/blog/' %}active{% endif %}">Blog</a>
      <div class="nav-item dropdown">
        <a href="#"
          class="
          nav-link dropdown-toggle
{#            {% if current_page == '/accreditation/' or current_page == '/member/' or current_page == '/hour/' %}#}
            {% if current_page == '/accreditation/'  or current_page == '/hour/' %}
                active
            {% endif %}
            "
          data-bs-toggle="dropdown"
          >Pages</a>
        <div class="dropdown-menu rounded-0 rounded-bottom m-0">
{#          <a href="animal.html" class="dropdown-item">Our Student</a>#}
{#            <a href="#" class="dropdown-item ">Our Student</a>#}
            <a href="{% url 'accreditation:index' %}" class="dropdown-item {% if current_page == '/accreditation/' %}active{% endif %}">Accreditation</a>
{#            <a href="#" class="dropdown-item">Homologation</a>#}
{#            <a href="{% url 'member:index' %}" class="dropdown-item {% if current_page == '/member/' %}active{% endif %}">Membership</a>#}
{#            <a href="#" class="dropdown-item">Testimonial</a>#}
            <a href="{% url 'hour:index' %}" class="dropdown-item {% if current_page == '/hour/' %}active{% endif %}">Visiting Hours</a>
{#          <a href="#" class="dropdown-item">404 Page</a>#}
        </div>
      </div>
      <a href="{% url 'price:index' %}" class="nav-item nav-link {% if current_page == '/price/' %}active{% endif %}">Pricing</a>
      <a href="{% url 'contact_us:index' %}" class="nav-item nav-link {% if current_page == '/contact/' %}active{% endif %}">Contact</a>
    </div>
    <a href="{% url 'register:index' %}" class="btn btn-primary"
      >Get Started<i class="fa fa-arrow-right ms-3"></i
    ></a>
  </div>
</nav>
<!-- Navbar End -->

templates/layouts/partials/_topbar.html
<!-- Topbar Start -->
<div class="container-fluid bg-light p-0 wow fadeIn" data-wow-delay="0.1s">
  <div class="row gx-0 d-none d-lg-flex">
    <div class="col-lg-6 px-5 text-start">
          {% for address in addresses_ahsm %}
      <div class="h-100 d-inline-flex align-items-center py-3 me-4">
            <small class="fa fa-map-marker-alt text-primary me-2"></small>
            <small>{{ address.lot }} {{ address.street }} {{ address.city }}</small>
      </div>
          {% endfor %}
      <div class="h-100 d-inline-flex align-items-center py-3">
        <small class="far fa-clock text-primary me-2"></small>
        <small>{{ hours_now }}</small>
      </div>
    </div>
    <div class="col-lg-6 px-5 text-end">
        {% for phone in contacts_helps %}
          <div class="h-100 d-inline-flex align-items-center py-3 me-4">
            <i class="fa fa-phone text-primary me-2"></i>
            <small>{{ phone.number }}</small>
          </div>
        {% endfor %}

        <div class="h-100 d-inline-flex align-items-center">
        {% if socials %}
        {% for social in socials %}
        <a class="btn btn-sm-square bg-white text-primary me-1" href="{{ social.url }}"
          ><i class="{{ social.social_type }}"></i
        ></a>
          {% endfor %}
        {% else %}
            <a class="btn btn-sm-square bg-white text-primary me-1" href="#"
          ></a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Topbar End -->